### ISSUE TITLE
FLAIR and Sig

### ISSUE THREAD

**Issue by Syphurith** [patois/NTRDisasm#1]
Hi patois. I don't know if you're using IDA Pro. If so, you can try to generate some signature files with FLAIR. Use `IDA2PAT Reloaded` for (.elf) or Official `FLAIR` from SDK for a library (.a). After used pelf or ida2pat and sigmake and conflicts solved, you get the .sig file. You can then put the .sig file to /sig/arm in IDA folder, and load it from `File->Load File->FILRT..`. If signature matches IDA would soon show up the functions in light blue. _In short, this helps you recover symbols._

```
#This generates libgcc.pat.
pelf libgcc.a
#This tried to generate the sig, with library name as libgcc.
sigmake -nlibgcc libgcc.pat libgcc.sig
#libgcc has conflicts, so it generated a libgcc.exc.
#I edited the file, and removed the comments in the first few lines of file.
sigmake -nlibgcc -xlibgcc.exc libgcc.pat libgcc.sig
```

Sometimes you would have to solve some conflicts, such as.

```
+__gnu_sssubsa3                                     0C 073F 000031E1001061E00100004A0100A0E11EFF2FE1000031E1FBFFFF5A000050E3
__gnu_sssubsq3                                      0C 073F 000031E1001061E00100004A0100A0E11EFF2FE1000031E1FBFFFF5A000050E3
```

_These step would be easier if use regex to place + for those firsts of each term._ To me i replaced `\r\n\r\n__` to `\r\n\r\n+__`, and the file is almost done.

Well. You might have to generate more sig files if there are some versions for its dependencies. For examples there are quite a few versions of libctru.
I like your work, much. Hope this helps you.. _Still trying to recover rxTools_.

**Comment by patois** [comment]
Thank you, I am familiar with IDA Pro but I do not have an SDK nor do I want it. Feel free to do whatever you want with the disassembly, tho. The IDC file can be used to import names and comments from my disassembly into your own IDA database.

**Comment by Syphurith** [comment]
@patois Thanks for replying me. If this isn't needed for you, i apologize cause i still think that's easier.

**Comment by Syphurith** [comment]
At least the IDC file doesn't work for me with 6.6. So it stops with an error...
BTW where is the start address for ntr.bin? is that 0x01000100 or 0x08000000..

**Comment by patois** [comment]
As far as I know there's no legal way to generate IDA signature files from the Nintendo SDK unless you're a certified developer.

The IDC file should work if you're using it on the correct ntr.bin file (AFAIR I've disassembled the "public beta 2.0" - check the disassembly for the ntr.bin CRC32 checksum and the MD5 hash). As for the start address, I currently don't remember the base address but you should be able to figure it out by looking at the disassembly. I think there's a variable I've named 'ntrbase' or something like that.

edit: by the way - having the ntr plugin sdk at hand while reversing it helps a lot, too :)

**Comment by patois** [comment]
@Syphurith https://github.com/patois/NTRDisasm/blob/master/disassembly/ntr.asm#L82
